spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.0.104:3306/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
#10.20.224.73
  #不希望虚拟机也打印数据库日志
#  jpa:
#    show-sql: true

#全局配置json显示的字符如果为空null则不显示
  jackson:
    default-property-inclusion: non_null

  redis:
#    host: 192.168.0.104
    host: 192.168.0.103
    port: 6379

#url的前缀
server:
  servlet:
    context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: D:/study/code/springbootOrder/var/log/tomcat/
#  file: D:/study/code/springbootOrder/var/log/tomcat/sell.log
#  level:
#     com.springboot.LoggerTest: debug
##    root: warn
##    org.springframework.web: debug

##    org.hibernate: error

wechat:
  # 公众账号, 授权
  mpAppId: wx73694811e68fd5db
  mpAppSecret: b207afb2655d325f27abae0243c84545

#注：如果借用别人的账号，支付openid和授权openid是分开的，你单独支付可以使用别人的，但是授权openid就要用自己的
#支付/商户号
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret:
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  #发起支付不需要证书，退款需要
  keyPath: D:/study/springstudy/springboot_order/h5.p12
  notifyUrl: http://qingfeng5.mynatapp.cc/sell/pay/notify

#开放平台买家扫码登录用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

project-url:
  wechatMpAuthorize: http://qingfeng5.mynatapp.cc
  wechatOpenAuthorize: http://qingfeng5.mynatapp.cc
  sell: http://qingfeng5.mynatapp.cc

#日志查看加入数据库的各项参数
logging:
  level:
    com.springboot.dataobject.mapper: trace

#xml加入数据库，查询数据
#xml这种不适用，不如mybatis注解
mybatis:
  mapper-locations: classpath:mapper/*.xml
